1) Indexing arrays
2) Array reference type vs copy function


In [1]:
import numpy as np 
## Accessing the array elements (Indexing - similar to how indexing was used to retrieve or access the elements the datastructures of lists, sets,
## tuples and dicts..lets learn how to access elements from numpy array.

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
## To access the number 4 from 1D array, we know that its index is 3 as the indexing starts from 0.
a[3]

4

In [3]:
## lets check how to access the elements from multi nested array..

multi = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(multi)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
## so the above 2D array has 3 rows and 4 columns...so to access elements 6,7,8..which row2 and column2,3,4..

## multi[ :, :]..to access elements from multi array. the values on left side colon reprsents rows and right side represents coluns..
## so to access row2 and coumn2,3,4..

multi[1,1:]

array([6, 7, 8])

In [5]:
## copy function and broadcasting...in below 1D array, im asking to replace all elements from 4th index to be replaced by 10..

a = np.array([1,2,3,4,5,6,7,8,9])
a[4:]=10
print(a)

b=a
print(b)
b[4:]=100
print(b)
print(a) 



[ 1  2  3  4 10 10 10 10 10]
[ 1  2  3  4 10 10 10 10 10]
[  1   2   3   4 100 100 100 100 100]
[  1   2   3   4 100 100 100 100 100]


In [6]:
## in here you can see that the variable a is also updated  same as b, this is because as array is reference type, which means
## that the 2 varaibles stored in same memory, which means any update on one variable will replicate that to other varriable aswell

## so to prevent that we have something called as copy()..i.e b is now creating another memory space of the a variable values, so its not being shared 
## from same memory

b=a.copy()
print(b)
b[4:]=0.0
print(b)
print(a)


[  1   2   3   4 100 100 100 100 100]
[1 2 3 4 0 0 0 0 0]
[  1   2   3   4 100 100 100 100 100]
