1) Import numpy
2) Convert lists into array
3) useful inbuilt functions - shape vs reshape


In [1]:
## first install numpy using the command "pip install numpy" Then import numpy library 

import numpy as np

In [2]:
## An exmaple showing converting list into an array using an array in-built function in numpy

list=[1,2,3,4,5,6]

list_to_array =np.array(list)

In [3]:
## from the output it can be seen that the list is converted into array which is 1D (one square bracket as oepning and one square bracket as closing) 
## and the elements are not separated by comma

print(list_to_array)


[1 2 3 4 5 6]


In [4]:
## we can also tell if its 1D , 2D or multi dimensional using shape function it tells the no of elements in rows and columns

list_to_array.shape

## here the output is 5 rows and no columns which is a 1D array..


(6,)

In [5]:
## the above 1D is converted to 2D array using an inbuilt reshape function where you tell the number of rows and columns..but make sure the total number 
## should be same i.e in 2D we have 6 elements, so to reshape, we can have 2x3 or 3x2 or 1x6, or 6x1


list_to_array.reshape(1,6)

## though the output visually looks like 1D, but its 2D because you can count 2 opening and closing square brackets

array([[1, 2, 3, 4, 5, 6]])

In [6]:
## Multi nested array (mna)
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[0,4,5,3,2,]

mna = np.array([list1,list2,list3])
print(mna)

## output here shows, 5 rows and 3 coulumns..we can check its shape
##  using shape function and also can reshape it 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  4  5  3  2]]


In [7]:
mna.shape

(3, 5)

In [8]:
mna.reshape(5,3)
## here you can see the above 3rows and 5columns has been reshaped
## for that we need to make sure total elements are same..ie 15, 
## only then it works...say if you have 12 elements, then it can be
## reshaped manyways as 3x4, 4x3, 2x6, 6x2, 1x12, 12x1 


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  0,  4],
       [ 5,  3,  2]])