## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
## first install numpy using the command "pip install numpy" Then import numpy library 

import numpy as np

In [2]:
## An exmaple showing converting list into an array using an array in-built function in numpy

list=[1,2,3,4,5,6]

list_to_array =np.array(list)

In [3]:
## from the output it can be seen that the list is converted into array which is 1D (one square bracket as oepning and one square bracket as closing) 
## and the elements are not separated by comma

print(list_to_array)


[1 2 3 4 5 6]


In [4]:
## we can also tell if its 1D , 2D or multi dimensional using shape function it tells the no of elements in rows and columns

list_to_array.shape

## here the output is 5 rows and no columns which is a 1D array..


(6,)

In [5]:
## the above 1D is converted to 2D array using an inbuilt reshape function where you tell the number of rows and columns..but make sure the total number 
## should be same i.e in 2D we have 6 elements, so to reshape, we can have 2x3 or 3x2 or 1x6, or 6x1


list_to_array.reshape(1,6)

## though the output visually looks like 1D, but its 2D because you can count 2 opening and closing square brackets

array([[1, 2, 3, 4, 5, 6]])

In [6]:
## Multi nested array (mna)
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[0,4,5,3,2,]

mna = np.array([list1,list2,list3])
print(mna)

## output here shows, 5 rows and 3 coulumns..we can check its shape
##  using shape function and also can reshape it 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  4  5  3  2]]


In [7]:
mna.shape

(3, 5)

In [8]:
mna.reshape(5,3)
## here you can see the above 3rows and 5columns has been reshaped
## for that we need to make sure total elements are same..ie 15, 
## only then it works...say if you have 12 elements, then it can be
## reshaped manyways as 3x4, 4x3, 2x6, 6x2, 1x12, 12x1 


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  0,  4],
       [ 5,  3,  2]])

In [9]:
## Accessing the array elements (Indexing - similar to how indexing was used to retrieve or access the elements the datastructures of lists, sets,
## tuples and dicts..lets learn how to access elements from numpy array.

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
## To access the number 4 from 1D array, we know that its index is 3 as the indexing starts from 0.
a[3]

4

In [11]:
## lets check how to access the elements from multi nested array..

multi = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(multi)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
## so the above 2D array has 3 rows and 4 columns...so to access elements 6,7,8..which row2 and column2,3,4..

## multi[ :, :]..to access elements from multi array. the values on left side colon reprsents rows and right side represents coluns..
## so to access row2 and coumn2,3,4..

multi[1,1:]

array([6, 7, 8])

In [13]:
## useful inbuilt functions of array..i,e arange...a range...start, stop and step of 2..this creates a 1D array

range = np.arange(0,10,2)
print(range)

## another useful inbuilt functions of array..i,e linspace...we use it in deep learning, sometimes we need to intiailise etc..that time we use this

linspace = np.linspace(0,5,num=10)
print(linspace)

[0 2 4 6 8]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [14]:
## copy function and broadcasting...in below 1D array, im asking to replace all elements from 4th index to be replaced by 10..

a = np.array([1,2,3,4,5,6,7,8,9])
a[4:]=10
print(a)

b=a
print(b)
b[4:]=100
print(b)
print(a) 



[ 1  2  3  4 10 10 10 10 10]
[ 1  2  3  4 10 10 10 10 10]
[  1   2   3   4 100 100 100 100 100]
[  1   2   3   4 100 100 100 100 100]


In [15]:
## in here you can see that the variable a is also updated  same as b, this is because as array is reference type, which means
## that the 2 varaibles stored in same memory, which means any update on one variable will replicate that to other varriable aswell

## so to prevent that we have something called as copy()..i.e b is now creating another memory space of the a variable values, so its not being shared 
## from same memory

b=a.copy()
print(b)
b[4:]=0.0
print(b)
print(a)


[  1   2   3   4 100 100 100 100 100]
[1 2 3 4 0 0 0 0 0]
[  1   2   3   4 100 100 100 100 100]


In [16]:
### Some conditions very useful in Exploratory Data Analysis 

value_check = np.array([10,2,50,4])
value_check>10

array([False, False,  True, False])

In [17]:
### if i want the valyes that are greater than 5, then we just need to put the condition in square bracket

value_check[value_check>10]

array([50])

In [18]:
mul = np.array([1,2,3,4])
mul*100

array([100, 200, 300, 400])

In [19]:
## Create arrays and reshape in one line...i.e range of numbers 1 to 12 using a range function and then reshape it to 1D 

np.arange(1,13).reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
## Create arrays and reshape in one line...i.e range of numbers 1 to 12 using a range function and then reshape it to 2D

np.arange(1,13).reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
## somemore useful inbuilt function is an np.ones...it creates an array that all elements are replaced by 1..
## by default dtype is float (you can change to int)...here it created 1D array 0f 4 elements with number 1 

np.ones(4) 

array([1., 1., 1., 1.])

In [22]:
## to create 2D array of np.ones

np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
## somemore inbuilt function...random distribution...rand function asking to select the sample based on unifrom distribution
np.random.rand(3,3)

array([[0.50377274, 0.35537046, 0.790313  ],
       [0.22023145, 0.2482135 , 0.18078556],
       [0.57808307, 0.85874183, 0.18720354]])

In [24]:
## randn saying that select the sample based on stanadard normal distribution
np.random.randn(4,4)

array([[ 1.21945783,  1.17938822,  0.07081785,  1.19033292],
       [ 1.36359835, -0.15927391, -0.17246341,  0.0092528 ],
       [-0.96618218,  0.35965643,  0.71295307, -0.81131242],
       [ 0.59076752,  1.72960207, -1.21607378, -0.61932753]])

In [25]:
## randn saying that select 8 integers from 0 to 100 range ...and make it 2D using reshape

np.random.randint(0,100,8).reshape(4,2)

array([[99, 61],
       [48, 30],
       [17, 96],
       [34, 27]])

In [26]:
np.random.random_sample((1,5))

array([[0.66143724, 0.76567094, 0.33150429, 0.41307138, 0.98077468]])