1) How conditions can be checked in arrays
2) Useful inbuilt functions - range, reshape, ones, 
3) some more useful random inbuilt functions - rand, randn, randint, random_sample


In [1]:
import numpy as np 
### Some conditions very useful in Exploratory Data Analysis 

value_check = np.array([10,2,50,4])
value_check>10

array([False, False,  True, False])

In [2]:
### if i want the valyes that are greater than 5, then we just need to put the condition in square bracket

value_check[value_check>10]

array([50])

In [3]:
mul = np.array([1,2,3,4])
mul*100

array([100, 200, 300, 400])

In [4]:

## useful inbuilt functions of array..i,e arange...a range...start, stop and step of 2..this creates a 1D array

range = np.arange(0,10,2)
print(range)

## another useful inbuilt functions of array..i,e linspace...we use it in deep learning, sometimes we need to intiailise etc..that time we use this

linspace = np.linspace(0,5,num=10)
print(linspace)

[0 2 4 6 8]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [5]:
## Create arrays and reshape in one line...i.e range of numbers 1 to 12 using a range function and then reshape it to 1D 

np.arange(1,13).reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
## Create arrays and reshape in one line...i.e range of numbers 1 to 12 using a range function and then reshape it to 2D

np.arange(1,13).reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
## somemore useful inbuilt function is an np.ones...it creates an array that all elements are replaced by 1..
## by default dtype is float (you can change to int)...here it created 1D array 0f 4 elements with number 1 

np.ones(4) 

array([1., 1., 1., 1.])

In [8]:
## to create 2D array of np.ones

np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
## somemore inbuilt function...random distribution...rand function asking to select the sample based on unifrom distribution
np.random.rand(3,3)

array([[0.49220027, 0.87261843, 0.22646672],
       [0.9796896 , 0.38970808, 0.30429087],
       [0.63419542, 0.86358452, 0.31241912]])

In [10]:
## randn saying that select the sample based on stanadard normal distribution
np.random.randn(4,4)

array([[ 0.04329441, -1.35390074,  0.23801599,  0.97447355],
       [ 0.63065738, -1.03414883, -2.23721319, -1.64280149],
       [ 1.54386148, -0.33152957,  0.01369108, -0.16518497],
       [ 0.83481849, -1.77358429, -1.26193731,  1.35253808]])

In [11]:
## randn saying that select 8 integers from 0 to 100 range ...and make it 2D using reshape

np.random.randint(0,100,8).reshape(4,2)

array([[18, 95],
       [96, 13],
       [ 2, 71],
       [22, 48]])

In [12]:
np.random.random_sample((1,5))

array([[0.2723349 , 0.58401421, 0.0084851 , 0.8292471 , 0.46891296]])